spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: Pratik39
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.fullstck.ecommerce.order.kafka.OrderConfirmation;
server:
  port: 8070

# API Gateway port for scalability purpose
application:
  config:
    customer-url: http://localhost:8039/api/v1/customers
    product-url: http://localhost:8039/api/v1/products
    payment-url: http://localhost:8039/api/v1/payments

#  Without API gateway , i can use individual ports but its used for local testing not for scalability purpose

#application:
#  config:
#    customer-url: http://localhost:8090/api/v1/customers
#    product-url: http://localhost:8050/api/v1/products
#    payment-url: http://localhost:8060/api/v1/payments
